### ISSUE TITLE
addSentShare fails on OC1

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/nc-sciencemesh#308] opened 2023-05-11 10:24 UTC
<img width="1395" alt="Screenshot 2023-05-11 at 12 22 21" src="https://github.com/pondersource/nc-sciencemesh/assets/408412/3926aee1-6009-42aa-b8e3-ec72b38afcc9">

```
2023-05-11 10:21:49.355 INF ../../workspace/dev-stock/reva/pkg/ocm/share/repository/nextcloud/nextcloud.go:424 > am.do https://oc1.docker/index.php/apps/sciencemesh/~einstein/api/ocm/addSentShare {"resourceId":{"storageId":"00000000-0000-0000-0000-000000000000","opaqueId":"fileid-/home/asdf"},"name":"asdf","token":"CHDamU2176kQWiXfUZ6CCZcHZcmcDyMg","grantee":{"type":"GRANTEE_TYPE_USER","userId":{"idp":"revanc2.docker","opaqueId":"marie"}},"owner":{"idp":"https://revaoc1.docker/","opaqueId":"einstein"},"creator":{"idp":"https://revaoc1.docker/","opaqueId":"einstein"},"ctime":{"seconds":"1683800509","nanos":355568072},"mtime":{"seconds":"1683800509","nanos":355568072},"shareType":"SHARE_TYPE_USER","accessMethods":[{"webdavOptions":{"permissions":{"getPath":true,"getQuota":true,"initiateFileDownload":true,"listGrants":true,"listContainer":true,"listFileVersions":true,"listRecycle":true,"stat":true}}},{"webappOptions":{"viewMode":"VIEW_MODE_READ_ONLY"}}]} pid=1 pkg=rgrpc traceid=28a3333c51f12b29a54b2869328aa066
2023-05-11 10:21:49.419 INF ../../workspace/dev-stock/reva/pkg/ocm/share/repository/nextcloud/nextcloud.go:445 > am.do response 500 <!DOCTYPE html>
```

```
[Thu May 11 10:23:44.631339 2023] [php7:notice] [pid 133] [client 172.18.0.2:54774] addSentShare array (\n  'userId' => 'einstein',\n  '_route' => 'sciencemesh.reva.addSentShare',\n  'resourceId' => \n  array (\n    'storageId' => '00000000-0000-0000-0000-000000000000',\n    'opaqueId' => 'fileid-/home/qwer',\n  ),\n  'name' => 'qwer',\n  'token' => 'mDzHSqy8gDl7BtFWj5oZ6NsaPquuCt4E',\n  'grantee' => \n  array (\n    'type' => 'GRANTEE_TYPE_USER',\n    'userId' => \n    array (\n      'idp' => 'revanc2.docker',\n      'opaqueId' => 'marie',\n    ),\n  ),\n  'owner' => \n  array (\n    'idp' => 'https://revaoc1.docker/',\n    'opaqueId' => 'einstein',\n  ),\n  'creator' => \n  array (\n    'idp' => 'https://revaoc1.docker/',\n    'opaqueId' => 'einstein',\n  ),\n  'ctime' => \n  array (\n    'seconds' => '1683800624',\n    'nanos' => 575259570,\n  ),\n  'mtime' => \n  array (\n    'seconds' => '1683800624',\n    'nanos' => 575259570,\n  ),\n  'shareType' => 'SHARE_TYPE_USER',\n  'accessMethods' => \n  array (\n    0 => \n    array (\n      'webdavOptions' => \n      array (\n        'permissions' => \n        array (\n          'getPath' => true,\n          'getQuota' => true,\n          'initiateFileDownload' => true,\n          'listGrants' => true,\n          'listContainer' => true,\n          'listFileVersions' => true,\n          'listRecycle' => true,\n          'stat' => true,\n        ),\n      ),\n    ),\n    1 => \n    array (\n      'webappOptions' => \n      array (\n        'viewMode' => 'VIEW_MODE_READ_ONLY',\n      ),\n    ),\n  ),\n)
[Thu May 11 10:23:44.631387 2023] [php7:notice] [pid 133] [client 172.18.0.2:54774] Interpreting /home/qwer as qwer
[Thu May 11 10:23:44.631937 2023] [php7:notice] [pid 133] [client 172.18.0.2:54774] calling newShare
[Thu May 11 10:23:44.638708 2023] [php7:notice] [pid 133] [client 172.18.0.2:54774] SMSP: createInternal
[Thu May 11 10:23:44.638739 2023] [php7:notice] [pid 133] [client 172.18.0.2:54774] shareWith marie@revanc2.docker
[Thu May 11 10:23:44.638753 2023] [php7:notice] [pid 133] [client 172.18.0.2:54774] checking if already shared qwer
[Thu May 11 10:23:45.004169 2023] [php7:notice] [pid 30] [client 172.18.0.9:39626] curl output:'{\n  "code": "ALREADY_EXIST",\n  "message": "internal error: {\\\\n  \\\\"code\\\\": \\\\"RESOURCE_NOT_FOUND\\\\",\\\\n  \\\\"message\\\\": \\\\"user not found\\\\"\\\\n}"\n}' info: array (\n  'url' => 'https://revaoc1.docker/sciencemesh/create-share',\n  'content_type' => 'application/json',\n  'http_code' => 409,\n  'header_size' => 717,\n  'request_size' => 208,\n  'filetime' => -1,\n  'ssl_verify_result' => 0,\n  'redirect_count' => 0,\n  'total_time' => 0.674075,\n  'namelookup_time' => 0.00071,\n  'connect_time' => 0.000945,\n  'pretransfer_time' => 0.012418,\n  'size_upload' => 182.0,\n  'size_download' => 138.0,\n  'speed_download' => 204.0,\n  'speed_upload' => 270.0,\n  'download_content_length' => 138.0,\n  'upload_content_length' => 182.0,\n  'starttransfer_time' => 0.012538,\n  'redirect_time' => 0.0,\n  'redirect_url' => '',\n  'primary_ip' => '172.18.0.2',\n  'certinfo' => \n  array (\n  ),\n  'primary_port' => 443,\n  'local_ip' => '172.18.0.4',\n  'local_port' => 33824,\n  'http_version' => 3,\n  'protocol' => 2,\n  'ssl_verifyresult' => 0,\n  'scheme' => 'HTTPS',\n  'appconnect_time_us' => 12219,\n  'connect_time_us' => 945,\n  'namelookup_time_us' => 710,\n  'pretransfer_time_us' => 12418,\n  'redirect_time_us' => 0,\n  'starttransfer_time_us' => 12538,\n  'total_time_us' => 674075,\n)
```

**Comment by parhamin2010** [comment] 2023-05-11 10:27
I already share folders and files. 
It's working well.

**Comment by MahdiBaghbani** [comment] 2023-05-18 17:41
@michielbdejong @mrvahedi68 I can't reproduce it now with the `webdav` option in reva toml files.

should we close this?

**Closed** 2023-05-19 07:53 UTC
