### ISSUE TITLE
(NB) contact list doesn't load and returns null from Reva request 

### ISSUE THREAD

**Issue by parhamin2010** [pondersource/nc-sciencemesh#286] opened 2023-04-27 14:33 UTC

**Comment by michielbdejong** [comment] 2023-04-27 17:21
Duplicate of https://github.com/pondersource/sciencemesh-php/issues/190, fixed

**Comment by parhamin2010** [comment] 2023-04-28 07:46
Here's where the contacts returing null. It seems from Reva side.
![image](https://user-images.githubusercontent.com/25672014/235086945-498300b4-63f2-48e1-bbad-03bcc22ed1db.png)

**Comment by michielbdejong** [comment] 2023-04-28 13:08
https://github.com/cs3org/reva/blob/master/internal/http/services/sciencemesh/sciencemesh.go#L107

**Comment by michielbdejong** [comment] 2023-04-28 13:11
not sure why this is a 404, the route looks correct to me? @parhamin2010 are you sure your reva is on the sciencemesh-dev branch and built?

**Comment by parhamin2010** [comment] 2023-04-28 13:15
![image](https://user-images.githubusercontent.com/25672014/235157574-ad77c831-5725-481c-9c10-0ee715dc7e62.png)

**Closed** 2023-05-19 07:54 UTC
